services:
  - type: web
    name: uomconnect-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: uomconnect-db
          property: connectionString
      - key: ADMIN_KEY
        generateValue: true       # Render generates a random value for you

databases:
  - name: uomconnect-db
    databaseName: uomconnect
    plan: free